myapp_yuzuri/urls.py
from django.urls import path
from . import views

app_name='myapp_yuzuri'

urlpatterns = [
    path('', views.index, name='index'),
    path('welcome', views.welcome, name='welcome'),
    path('like', views.like, name='like'),
    path('dislike', views.dislike, name='dislike'),
    path('birthday', views.birthday, name='birthday'),
]

myproject_yuzuri/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp_yuzuri.urls'))
]

myapp_yuzuri/models.py
from django.db import models

# Create your models here.

myapp_yuzuri/views.py
# Create your views here.
from django.shortcuts import render # render関数

def index(request): # index関数
    return render(request,'index.html') # index.htmlを返す

def welcome(request): # welcome関数
	return render(request, 'welcome.html') # welcome.htmlを返す

def like(request): # like関数
    return render(request,'like.html') # like.htmlを返す

def dislike(request): # dislike関数
    return render(request,'dislike.html') # dislike.htmlを返す

def birthday(request): # birthday関数
    return render(request,'birthday.html') # birthday.htmlを返す

myapp_yuzuri/templates/dislike.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="style.css">

        <title>我が家の愛犬ポチの日記</title>
    </head>

    <body>
        <h1>我が家の愛犬ポチの日記</h1>

        <h2>うちの可愛い愛犬ポチを紹介するホームページです。</h2>

        <p>可愛いわんちゃんがうちに来てくれました</p>
        <p>ポチの好きな食べ物</p>
        <p>ポチの嫌いな食べ物</p>
        <p>ポチが１才になりました</p>
    </body>

</html>

myapp_yuzuri/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static "css/style.css" %}"/>

        <title>我が家の愛犬ポチの日記</title>

    </head>

    <body>

        <h1>我が家の愛犬ポチの日記</h1>

        <img src="{% static "images/av1.jpg" %}" alt="表示できません">
        <img src="{% static "images/av2.jpg" %}" alt="表示できません">
        <img src="{% static "images/av3.jpg" %}" alt="表示できません">
        <img src="{% static "images/av4.jpg" %}" alt="表示できません">

        <h2>うちの可愛い愛犬ポチを紹介するホームページです。</h2>

        <p><a href="{% url 'myapp_yuzuri:welcome' %}">可愛いわんちゃんがうちに来てくれました</a></p>
        <p><a href="{% url 'myapp_yuzuri:like' %}">ポチの好きな食べ物</a></p>
        <p><a href="{% url 'myapp_yuzuri:dislike' %}">ポチの嫌いな食べ物</a></p>
        <p><a href="{% url 'myapp_yuzuri:birthday' %}">ポチが１才になりました</a></p>

    </body>

</html>

myapp_yuzuri/templates/welcome.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="style.css">

        <title>我が家の愛犬ポチの日記</title>
    </head>

    <body>
        <h1>我が家の愛犬ポチの日記</h1>



        <h2>うちの可愛い愛犬ポチを紹介するホームページです。</h2>

        <p>可愛いわんちゃんがうちに来てくれました</p>
        <p>ポチの好きな食べ物</p>
        <p>ポチの嫌いな食べ物</p>
        <p>ポチが１才になりました</p>
    </body>

</html>